stages:
  data_reader:
    cmd: python ml_dev/data_reader.py
    deps:
    - ml_dev/data_reader.py
    outs:
    - data/processed/train_df.csv
    - data/processed/test_df.csv
  preprocessing:
    cmd: python ml_dev/preprocessing.py
    deps:
    - ml_dev/preprocessing.py
    - data/processed/train_df.csv
    - data/processed/test_df.csv
    outs:
    - data/processed/pre_train_df.csv
    - data/processed/pre_test_df.csv
  feature_selection:
    cmd: python ml_dev/feature_selection.py
    deps: 
    - ml_dev/feature_selection.py
    - data/processed/pre_train_df.csv
    outs:
    - bin/best_features.pkl
  train:
    cmd: python ml_dev/train.py
    deps:
    - ml_dev/train.py
    - data/processed/pre_train_df.csv
    - data/processed/pre_test_df.csv
    - bin/best_features.pkl
    outs:
    - bin/hyperparams.pkl
    - bin/model.pkl
  evaluate:
    cmd: python ml_dev/evaluate.py
    deps:
    - ml_dev/evaluate.py
    - data/processed/pre_test_df.csv
    - bin/best_features.pkl
    - bin/model.pkl
    outs:
    - data/metrics.yaml
    - data/confusion_matrix.png