base:
  seed: 42

data_preprocess:
  source_directory: data/external
  destination_directory: data/processed
  artifact_directory: bin/

train:
  test_size: 0.15
  trails: 5
  label: price_range
  mi_threshold: 0.01
  multiclass_technique: ovr
  average: micro
